name: CI/CD to Kubernetes via ArgoCD

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: toothless2018/gitops-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|" k8s/helm-chart/values.yaml

      - name: Commit and push updated values.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "landians"
          git config user.email "1309603587@qq.com"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          
          git add k8s/helm-chart/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin HEAD:${{ github.ref_name }}